Repository carsondrobe/Fellas, pull requests merged in 2024-04, with the labels that each got.

#200 combine wind speed and gust, delete unused image
  Site/bc_weather_station_dashboard/website/static/JavaScript/map.js
  Site/bc_weather_station_dashboard/website/static/JavaScript/wind_speed.js
  Site/bc_weather_station_dashboard/website/static/bc_map.jpeg
  Site/bc_weather_station_dashboard/website/templates/weather.html
  Site/bc_weather_station_dashboard/website/tests/abi/map.test.js
  Site/bc_weather_station_dashboard/website/tests/carson/wind_speedTest.js
Labels: task

#206 Basic weather alerts
  .github/workflows/csv_scrape.yml
  .github/workflows/django.yml
  Site/bc_weather_station_dashboard/website/management/commands/csv_scrape.py
  Site/bc_weather_station_dashboard/website/migrations/0005_remove_alert_station_data_remove_alert_user_and_more.py
  Site/bc_weather_station_dashboard/website/models.py
  Site/bc_weather_station_dashboard/website/static/forms.js
  Site/bc_weather_station_dashboard/website/templates/modals.html
  Site/bc_weather_station_dashboard/website/tests.py
Labels: feature, task

#207 205 add prediction button
  Site/bc_weather_station_dashboard/website/templates/fire.html
  Site/bc_weather_station_dashboard/website/templates/navbar.html
  Site/bc_weather_station_dashboard/website/templates/weather.html
Labels: task

#227 154 date switching bug
  Site/bc_weather_station_dashboard/website/static/JavaScript/map.js
  Site/bc_weather_station_dashboard/website/templates/fire.html
  Site/bc_weather_station_dashboard/website/templates/navbar.html
  Site/bc_weather_station_dashboard/website/templates/weather.html
  Site/bc_weather_station_dashboard/website/tests/abi/map.test.js
Labels: bug

#228 Alerts modal
  Site/bc_weather_station_dashboard/website/templates/alerts.html
  Site/bc_weather_station_dashboard/website/templates/navbar.html
  Site/bc_weather_station_dashboard/website/urls.py
  Site/bc_weather_station_dashboard/website/views.py
Labels: feature

#215 Last updated badge
  Site/bc_weather_station_dashboard/website/static/CSS/home.css
  Site/bc_weather_station_dashboard/website/static/JavaScript/map.js
  Site/bc_weather_station_dashboard/website/static/home.js
  Site/bc_weather_station_dashboard/website/templates/fire.html
  Site/bc_weather_station_dashboard/website/templates/modals.html
  Site/bc_weather_station_dashboard/website/templates/weather.html
  Site/bc_weather_station_dashboard/website/tests/abi/map.test.js
  Site/bc_weather_station_dashboard/website/views.py
Labels: feature

#231 Hourly temp dynamic colour
  Site/bc_weather_station_dashboard/website/static/JavaScript/map.js
  Site/bc_weather_station_dashboard/website/templates/weather.html
  Site/bc_weather_station_dashboard/website/tests/abi/map.test.js
Labels: feature

#193 Finalizing widget layout and implementation of mobile view.
  Site/bc_weather_station_dashboard/bc_weather_station_dashboard/settings.py
  Site/bc_weather_station_dashboard/website/static/CSS/fire_widgets.css
  Site/bc_weather_station_dashboard/website/static/JavaScript/map.js
  Site/bc_weather_station_dashboard/website/static/WidgetJavaScript/bui.js
  Site/bc_weather_station_dashboard/website/static/WidgetJavaScript/danger_rating.js
  Site/bc_weather_station_dashboard/website/static/WidgetJavaScript/dc.js
  Site/bc_weather_station_dashboard/website/static/WidgetJavaScript/dmc.js
  Site/bc_weather_station_dashboard/website/static/WidgetJavaScript/ffmc.js
  Site/bc_weather_station_dashboard/website/static/WidgetJavaScript/snow_depth.js
  Site/bc_weather_station_dashboard/website/static/WidgetJavaScript/wind_direction.js
  Site/bc_weather_station_dashboard/website/static/images/snow_container.svg
  Site/bc_weather_station_dashboard/website/static/images/snow_container_empty.svg
  Site/bc_weather_station_dashboard/website/templates/fire.html
  Site/bc_weather_station_dashboard/website/templates/navbar.html
  Site/bc_weather_station_dashboard/website/templates/weather.html
  Site/bc_weather_station_dashboard/website/tests/abi/map.test.js
  Site/bc_weather_station_dashboard/website/tests/davis/fire_tests.js
  Site/bc_weather_station_dashboard/website/tests/robert/wind_directionTest.js
  Site/bc_weather_station_dashboard/website/views.py
Labels: feature, exploration

#237 236 spacing fixes
  Site/bc_weather_station_dashboard/bc_weather_station_dashboard/settings.py
  Site/bc_weather_station_dashboard/website/static/dataLogic/map.js
  Site/bc_weather_station_dashboard/website/static/placeholder_widgets/BI.png
  Site/bc_weather_station_dashboard/website/static/placeholder_widgets/DC.png
  Site/bc_weather_station_dashboard/website/static/placeholder_widgets/DMC.png
  Site/bc_weather_station_dashboard/website/static/placeholder_widgets/FFMC.png
  Site/bc_weather_station_dashboard/website/static/placeholder_widgets/FWI.png
  Site/bc_weather_station_dashboard/website/static/placeholder_widgets/ISI.png
  Site/bc_weather_station_dashboard/website/static/widgetsJS/fire/bui.js
  Site/bc_weather_station_dashboard/website/static/widgetsJS/fire/danger_rating.js
  Site/bc_weather_station_dashboard/website/static/widgetsJS/fire/dc.js
  Site/bc_weather_station_dashboard/website/static/widgetsJS/fire/dmc.js
  Site/bc_weather_station_dashboard/website/static/widgetsJS/fire/ffmc.js
  Site/bc_weather_station_dashboard/website/static/widgetsJS/fire/fwi.js
  Site/bc_weather_station_dashboard/website/static/widgetsJS/fire/isi.js
  Site/bc_weather_station_dashboard/website/static/widgetsJS/weather/humidity.js
  Site/bc_weather_station_dashboard/website/static/widgetsJS/weather/precipitation.js
  Site/bc_weather_station_dashboard/website/static/widgetsJS/weather/snow_depth.js
  Site/bc_weather_station_dashboard/website/static/widgetsJS/weather/wind_direction.js
  Site/bc_weather_station_dashboard/website/static/widgetsJS/weather/wind_speed.js
  Site/bc_weather_station_dashboard/website/templates/fire.html
  Site/bc_weather_station_dashboard/website/templates/navbar.html
  Site/bc_weather_station_dashboard/website/templates/view_favourites.html
  Site/bc_weather_station_dashboard/website/templates/weather.html
  Site/bc_weather_station_dashboard/website/tests/Qunit/humidityTest.js
  Site/bc_weather_station_dashboard/website/tests/abi/map.test.js
  Site/bc_weather_station_dashboard/website/tests/abi2/precipitationTest.js
  Site/bc_weather_station_dashboard/website/tests/carson/wind_speedTest.js
  Site/bc_weather_station_dashboard/website/tests/davis/fire_tests.js
  Site/bc_weather_station_dashboard/website/tests/fire_tests.js
  Site/bc_weather_station_dashboard/website/tests/robert/humidityTest.js
  Site/bc_weather_station_dashboard/website/tests/robert/wind_directionTest.js
  Site/bc_weather_station_dashboard/website/tests/wind_directionTest.js
Labels: bug
