Repository carsondrobe/Fellas, pull requests merged in 2024-03, with the labels that each got.

#95 Added second page and button to swap
  Site/bc_weather_station_dashboard/website/map.test.js
  Site/bc_weather_station_dashboard/website/static/flame_icon.svg
  Site/bc_weather_station_dashboard/website/static/home.css
  Site/bc_weather_station_dashboard/website/static/placeholder_widgets/BI.png
  Site/bc_weather_station_dashboard/website/static/placeholder_widgets/DC.png
  Site/bc_weather_station_dashboard/website/static/placeholder_widgets/DMC.png
  Site/bc_weather_station_dashboard/website/static/placeholder_widgets/FFMC.png
  Site/bc_weather_station_dashboard/website/static/placeholder_widgets/FWI.png
  Site/bc_weather_station_dashboard/website/static/placeholder_widgets/ISI.png
  Site/bc_weather_station_dashboard/website/static/weather_icon.svg
  Site/bc_weather_station_dashboard/website/templates/fire.html
  Site/bc_weather_station_dashboard/website/templates/navbar.html
  Site/bc_weather_station_dashboard/website/templates/weather.html
  Site/bc_weather_station_dashboard/website/tests.py
  Site/bc_weather_station_dashboard/website/urls.py
  Site/bc_weather_station_dashboard/website/views.py
Labels: feature

#121 CI/CD Github Actions: Create django.yml
  .github/workflows/django.yml
  .gitignore
  Site/bc_weather_station_dashboard/website/tests.py
  requirements.txt
Labels: Chore

#110 Dark Mode
  Site/bc_weather_station_dashboard/website/static/CSS/fire_widgets.css
  Site/bc_weather_station_dashboard/website/static/home.css
  Site/bc_weather_station_dashboard/website/static/images/calendar_icon.svg
  Site/bc_weather_station_dashboard/website/static/images/flame_icon.svg
  Site/bc_weather_station_dashboard/website/static/images/snow_container.svg
  Site/bc_weather_station_dashboard/website/static/images/weather_icon.svg
  Site/bc_weather_station_dashboard/website/static/images/weather_station_icon.svg
  Site/bc_weather_station_dashboard/website/static/map.js
  Site/bc_weather_station_dashboard/website/static/wind_direction.js
  Site/bc_weather_station_dashboard/website/templates/fire.html
  Site/bc_weather_station_dashboard/website/templates/modals.html
  Site/bc_weather_station_dashboard/website/templates/navbar.html
  Site/bc_weather_station_dashboard/website/templates/weather.html
Labels: exploration

#167 Add week 11 scrum doc
  ScrumMeetings/week_11.docx
  ScrumMeetings/week_11.pdf
Labels: Chore

#177 wind speed widget
  .github/workflows/django.yml
  Site/bc_weather_station_dashboard/package.json
  Site/bc_weather_station_dashboard/website/__pycache__/models.cpython-311.pyc
  Site/bc_weather_station_dashboard/website/__pycache__/urls.cpython-311.pyc
  Site/bc_weather_station_dashboard/website/__pycache__/views.cpython-311.pyc
  Site/bc_weather_station_dashboard/website/static/JavaScript/map.js
  Site/bc_weather_station_dashboard/website/static/JavaScript/wind_speed.js
  Site/bc_weather_station_dashboard/website/static/home.css
  Site/bc_weather_station_dashboard/website/static/images/wind-icon.svg
  Site/bc_weather_station_dashboard/website/templates/weather.html
  Site/bc_weather_station_dashboard/website/tests/abi/map.test.js
  Site/bc_weather_station_dashboard/website/tests/carson/wind_speedTest.js
Labels: task

#191 Add week 12 scrum
  ScrumMeetings/week_12.docx
  ScrumMeetings/week_12.pdf
Labels: Chore

#187 137 scale fire widgets
  Site/bc_weather_station_dashboard/website/static/CSS/fire_widgets.css
  Site/bc_weather_station_dashboard/website/static/JavaScript/isi 2.js
  Site/bc_weather_station_dashboard/website/templates/fire.html
  Site/bc_weather_station_dashboard/website/templates/weather.html
Labels: task

#189 176-add-favourite-station-functionality
  Site/bc_weather_station_dashboard/website/static/CSS/favourite_cards.css
  Site/bc_weather_station_dashboard/website/static/JavaScript/map.js
  Site/bc_weather_station_dashboard/website/templates/navbar.html
  Site/bc_weather_station_dashboard/website/templates/view_favourites.html
  Site/bc_weather_station_dashboard/website/templates/weather.html
  Site/bc_weather_station_dashboard/website/tests.py
  Site/bc_weather_station_dashboard/website/urls.py
  Site/bc_weather_station_dashboard/website/views.py
Labels: feature

#192 42 automate csv scrape
  .github/workflows/csv_scrape.yml
  .gitignore
  Site/bc_weather_station_dashboard/bc_weather_station_dashboard/__pycache__/settings.cpython-310.pyc
  Site/bc_weather_station_dashboard/bc_weather_station_dashboard/__pycache__/urls.cpython-310.pyc
  Site/bc_weather_station_dashboard/website/__pycache__/admin.cpython-310.pyc
  Site/bc_weather_station_dashboard/website/__pycache__/models.cpython-310.pyc
  Site/bc_weather_station_dashboard/website/__pycache__/urls.cpython-310.pyc
  Site/bc_weather_station_dashboard/website/__pycache__/views.cpython-310.pyc
  Site/bc_weather_station_dashboard/website/migrations/__pycache__/0001_initial.cpython-310.pyc
Labels: feature

#186 Precipitation Widget HTML & Logic & Tests, Search Bar Colours, Page Toggle Sticky
  .github/workflows/django.yml
  Site/bc_weather_station_dashboard/package.json
  Site/bc_weather_station_dashboard/website/static/CSS/precipitation_card.css
  Site/bc_weather_station_dashboard/website/static/CSS/search_bar.css
  Site/bc_weather_station_dashboard/website/static/JavaScript/map.js
  Site/bc_weather_station_dashboard/website/static/JavaScript/precipitation.js
  Site/bc_weather_station_dashboard/website/static/home.css
  Site/bc_weather_station_dashboard/website/templates/fire.html
  Site/bc_weather_station_dashboard/website/templates/weather.html
  Site/bc_weather_station_dashboard/website/tests/abi/map.test.js
  Site/bc_weather_station_dashboard/website/tests/abi2/precipitationTest.js
Labels: bug, task
